version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: kochimetro
      POSTGRES_USER: metro_user
      POSTGRES_PASSWORD: metro_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metro_user -d kochimetro"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
